[project]
name = "auralmind_masters"
version = "0.0.1"
description = "Auralmind Masters MCP Server automates hifidelity mastering process"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "httpx>=0.28.1",
    "mcp[cli]>=1.26.0",
]
